events { worker_connections 1024; }

http {
    upstream streamlits {
        ip_hash;
        server wocsat-app:8501;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://streamlits;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            
            # WebSocket support
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
}