services:
  cai:
    build:
      context: ./cai
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    networks:
      - cai
    environment:
      OPENAI_API_KEY: "sk-1234"
      ANTHROPIC_API_KEY: ""
      OLLAMA: ""
      PROMPT_TOOLKIT_NO_CPR: "1"

  mcp-server:
    build:
      context: ./mcp-server
      dockerfile: Dockerfile
    networks:
      - cai

networks:
  cai:
    driver: bridge