interface=ap0
bind-interfaces
listen-address=192.168.50.1
dhcp-range=192.168.50.10,192.168.1.100,8h
dhcp-option=3,192.168.1.1  # Définit votre IP comme passerelle
dhcp-option=6,8.8.8.8      # Utilise le DNS de Google
